version: "3"
services:
  db:
    image: mongo:4
    ports:
      - 3012:27017
    volumes:
      - dbdata:/data/db
      - ./db:/home/db
    working_dir: /home/db
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  dbdata:
    driver: local